

user  nobody;
worker_processes  2;

error_log  HOME/bin/nginx/logs/error.log notice;
pid        HOME/bin/nginx/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       "HOME/bin/nginx/conf/mime.types";
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  HOME/bin/nginx/logs/access.log  main;

    sendfile        on;
    client_max_body_size 1024M;
    keepalive_timeout  65;


    server {
        listen       443 ssl ;
        server_name  DYNV6_DNS;

        root         "HOME/bin/nginx/html";

        ssl_certificate     "HOME/bin/nginx/conf/ssl/fullchain.cer";
        ssl_certificate_key "HOME/bin/nginx/conf/ssl/DYNV6_DNS.key";
        ssl_session_cache shared:SSL:1m;
        ssl_session_timeout  10m;
        ssl_ciphers HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers on;

        include HOME/bin/nginx/conf/conf.d/*.conf;

    }

}
