
    server {
        listen       443 ssl ;
        server_name  openlist.DYNV6_DNS;

        root         "HOME/bin/nginx/html";

        ssl_certificate     "HOME/bin/nginx/conf/ssl/fullchain.cer";
        ssl_certificate_key "HOME/bin/nginx/conf/ssl/DYNV6_DNS.key";
        ssl_session_cache shared:SSL:1m;
        ssl_session_timeout  10m;
        ssl_ciphers HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers on;

        location / {
        proxy_set_header HOST $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_pass http://127.0.0.1:5244;
        }

    }
